=== JoelJimenezDAW/ExamenDLL/examen.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xsd:element name="examenddl" type="tipoexamen"/>

    <xsd:complexType name="tipoexamen">
        <xsd:sequence>
            <xsd:element name ="Resultados" type="tiporesultado" maxOccurs="unbounded"/>




        </xsd:sequence>
    </xsd:complexType>







    <xsd:element name="CriterioValoracion">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Id_aspirante" type="xs:integer"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="Examen">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Id_aspirante" type="xs:integer"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    
    <xsd:complexType name="tiporesultado">
            <xsd:sequence>
                <xsd:element name="Id_aspirante" type="xs:integer"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>


    <xsd:element name="aspirante">
            <xsd:complexType>
                <xsd:sequence>
                    <xsd:element name="Id_aspirante" type="xs:integer"/>
                    <xsd:element name="Nombres" type="xs:string"/>
                    <xsd:element name="Apellidos" type="xs:string"/>
                    <xsd:element name="DNI" type="xs:string"/>
                    <xsd:element name="Telefono" type="xs:string"/>
                    <xsd:element name="Direccion" type="xs:string"/>
                    <xsd:element name="Fecha_nacimiento" type="xs:string"/>
                    <xsd:element name="Dan" type="xs:string"/>
                    <xsd:element name="Cinturon" type="xs:string"/>
                    <xsd:element name="Fecha_Ingreso_Dan" type="xs:string"/>
                    <xsd:element name="FotoAspirante" type="xs:string"/>
                    <xsd:element name="Tiempo_Dan_Anterior" type="xs:string"/>
                    <xsd:element name="FotoDNI" type="xs:string"/>
                    <xsd:element name="FotoCarnetGrados" type="xs:string"/>
                </xsd:sequence>
            </xsd:complexType>
    </xsd:element>
        
        

    <xsd:element name="Meritos">
        <xsd:complexType>
            <xsd:sequence>
            <xsd:element name="Id_aspirante" type="xs:integer"/>
            <xsd:element name="Edad_aspirante" type="xs:integer"/>
            <xsd:element name="LicenciaActualizada" type="xs:boolean"/>
            <xsd:element name="TrabajoEscrito" type="xs:boolean"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>



    <xsd:element name="Convalidacion_Grados">
        <xsd:complexType>
            <xsd:sequence>
            <xsd:element name="Id_aspirante" type="xs:integer"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>



    <xsd:element name="Requisitos_Aspirantes">
        <xsd:complexType>
            <xsd:sequence>
            <xsd:element name="SolicitudHasta3Dan" type="xs:boolean"/>
            <xsd:element name="D4anySuperiorCurriculum" type="xs:boolean"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>



    <xsd:element name="DispensaMedica">
        <xsd:complexType>
                <xsd:sequence>
                <xsd:element name="Id_aspirante" type="xs:integer"/>
                </xsd:sequence>
        </xsd:complexType>
    </xsd:element>



    <xsd:element name="Jueces">
        <xsd:complexType>
                    <xsd:sequence>
                    <xsd:element name="Id_aspirante" type="xs:integer"/>
                    <xsd:element name="Nombres" type="xs:string"/>
                    <xsd:element name="Apellidos" type="xs:string"/>
                    <xsd:element name="DiplomaJuez" type="xs:boolean"/>
                    </xsd:sequence>
        </xsd:complexType>
    </xsd:element>



    <xsd:element name="Criterio_Valoracion">
        <xsd:complexType>
                <xsd:sequence>
                <xsd:element name="Indumentaria" type="xs:integer"/>
                <xsd:element name="AseoPersonal" type="xs:integer"/>
                <xsd:element name="EjecucionTecnica" type="xs:integer"/>
                <xsd:element name="Valores" type="xs:integer"/>
                <xsd:element name="Respuestas" type="xs:integer"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>



    <xsd:element name="Tribunal">
            <xsd:complexType>
                    <xsd:sequence>
                    <xsd:element name="Numero_jueces" type="xs:integer"/>
                    <xsd:element name="Calificacion_final" type="xs:integer"/>
                    </xsd:sequence>
            </xsd:complexType>
    </xsd:element>



    <xsd:element name="AbonarCuota">
            <xsd:complexType>
                <xsd:sequence>
                    <xsd:element name="Id_aspirante" type="xs:integer"/>
                </xsd:sequence>
            </xsd:complexType>
    </xsd:element>

    <xsd:element name="SuspendeExamen">
            <xsd:complexType>
                <xsd:sequence>
                    <xsd:element name="Id_aspirante" type="xs:integer"/>
                    <xsd:element name="SuspendeParcial" type="xs:boolean"/>
                    <xsd:element name="SuspendeTotal" type="xs:boolean"/>
                    <xsd:element name="SuspendeSegundaFase" type="xs:boolean"/>
                </xsd:sequence>
            </xsd:complexType>
    </xsd:element>

    <xsd:element name="Hasta3erDan">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Tecnicas" type="xs:string"/>
                <xsd:element name="Kata" type="xs:string"/>
                <xsd:element name="Kumite" type="xs:string"/>
                <xsd:element name="Campeonatos" type="xs:string"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="CinturonNegro">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Tecnica_Directa" type="xs:string"/>
                <xsd:element name="Tecnica_Circulares" type="xs:string"/>
                <xsd:element name="Tecnica_Pierna" type="xs:string"/>
                <xsd:element name="Teoria" type="xs:string"/>
                <xsd:element name="Kata" type="xs:string"/>
                <xsd:element name="Kumite" type="xs:string"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="CinturonNegroPrimerDan">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Tecnica_Defensa" type="xs:string"/>
                <xsd:element name="Tecnica_Pierna" type="xs:string"/>
                <xsd:element name="Tecnica_DirectaIndirecta" type="xs:string"/>
                <xsd:element name="Tecnica_Combinada" type="xs:string"/>
                <xsd:element name="Teoria" type="xs:string"/>
                <xsd:element name="Kata" type="xs:string"/>
                <xsd:element name="Kumite" type="xs:string"/>
                <xsd:element name="Aplicación_Tecnica" type="xs:string"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="CinturonNegroSegundoDan">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Tecnica_Base" type="xs:string"/>
                <xsd:element name="Tecnica_Directa" type="xs:string"/>
                <xsd:element name="Tecnica_IndirectaCircular" type="xs:string"/>
                <xsd:element name="Tecnica_Pierna" type="xs:string"/>
                <xsd:element name="Tecnica_Combinada" type="xs:string"/>
                <xsd:element name="Teoria" type="xs:string"/>
                <xsd:element name="Kata" type="xs:string"/>
                <xsd:element name="Kumite" type="xs:string"/>
                <xsd:element name="Campeonatos" type="xs:string"/>
                <xsd:element name="Tecnicas" type="xs:string"/>
                <xsd:element name="Aplicación_Tecnica" type="xs:string"/>
                <xsd:element name="Demo_libre" type="xs:string"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="CinturonNegroTercerDan">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Variaciones_Tecnica" type="xs:string"/>
                <xsd:element name="Teoria" type="xs:string"/>
                <xsd:element name="Kata" type="xs:string"/>
                <xsd:element name="Kumite" type="xs:string"/>
                <xsd:element name="Campeonatos" type="xs:string"/>
                <xsd:element name="Tecnicas" type="xs:string"/>
                <xsd:element name="Aplicaciones" type="xs:string"/>
                <xsd:element name="Aplicacion_Tecnica" type="xs:string"/>
                <xsd:element name="Demo_libre" type="xs:string"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="CinturonNegroCuartoDan">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Kata" type="xs:string"/>
                <xsd:element name="Kumite" type="xs:string"/>
                <xsd:element name="Coloquio" type="xs:string"/>
                <xsd:element name="Aplicacion_Tecnica" type="xs:string"/>
                <xsd:element name="Demo_libre" type="xs:string"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="QuintoDanySuperior">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Kata" type="xs:string"/>
                <xsd:element name="Coloquio" type="xs:string"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== JoelJimenezDAW/ExamenDLL/exmaneDLL.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="decoracion.css"?>
<examenddl xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="examen.xsd">

<Resultados>
        <Id_aspirante>001</Id_aspirante> 
</Resultados>


<Aspirantes>
        <Id_aspirante>001</Id_aspirante>
        <Nombres>Joe</Nombres>
        <Apellidos>Hernandez Gona</Apellidos>
        <DNI>1243568R</DNI>
        <Telefono>565153456</Telefono>
        <Direccion>Calle Rencor, 20</Direccion>
        <Fecha_nacimiento>19/02/2002</Fecha_nacimiento>
        <Dan>Primero Dan</Dan>
        <Cinturon>Cinturon negro</Cinturon>
        <Fecha_Ingreso_Dan>23/03/2019</Fecha_Ingreso_Dan>
        <FotoAspirante>FotoAspirante.png</FotoAspirante>
        <Tiempo_Dan_Anterior>3 meses</Tiempo_Dan_Anterior>
        <FotoDNI>FotoDni1.png</FotoDNI>
        <FotoCarnetGrados>FotoCarnetGrados1.png</FotoCarnetGrados>
</Aspirantes>

<CriterioValoraciones>
        <Indumentaria>9</Indumentaria>
        <AseoPersonal>8</AseoPersonal>
        <EjecucionTecnica>10</EjecucionTecnica>
        <Valores>9</Valores>
        <Respuestas>10</Respuestas>
</CriterioValoraciones>

<Examenes>
        <Id_aspirante>001</Id_aspirante> 
</Examenes>

<Meritos2>
        <Id_aspirante>001</Id_aspirante>
        <Edad_aspirante>18</Edad_aspirante>
        <LicenciaActualizada>false</LicenciaActualizada>
        <TrabajoEscrito>true</TrabajoEscrito>
</Meritos2>


<ConvalidacionesGrados>
        <Id_aspirante>001</Id_aspirante>
</ConvalidacionesGrados> 

<RequisitosAspirantes>
        <SolicitudHasta3Dan>true</SolicitudHasta3Dan>
        <D4anySuperiorCurriculum>true</D4anySuperiorCurriculum>
</RequisitosAspirantes>

<DispensaMedicas>
        <Id_aspirante>001</Id_aspirante>
</DispensaMedicas>

<Jueces>
        <Id_aspirante>001</Id_aspirante>
        <Nombres>Joel</Nombres>
        <Apellidos>Jimenez Genius</Apellidos>
        <DiplomaJuez>true</DiplomaJuez>
</Jueces>

<Tribunales>
        <Numero_jueces>1</Numero_jueces>
        <Calificacion_final>8</Calificacion_final>
</Tribunales>

<AbonarCuotas>
        <Id_aspirante>001</Id_aspirante>
</AbonarCuotas>

<SuspendeExamen>
        <Id_aspirante>001</Id_aspirante>
        <SuspendeParcial>false</SuspendeParcial>
        <SuspendeTotal>false</SuspendeTotal>
        <SuspendeSegundaFase>false</SuspendeSegundaFase>
</SuspendeExamen>

<Hasta3erDanes>
        <Tecnicas>Kakato geri</Tecnicas>
        <Kata>ataque</Kata>
        <Kumite>real</Kumite>
        <Campeonatos>Karate</Campeonatos>
</Hasta3erDanes>

<CinturonNegros>
        <Tecnica_Directa>TSUKI-UCHI WAZA</Tecnica_Directa>
        <Tecnica_Circulares>Mawashi geri</Tecnica_Circulares>
        <Tecnica_Pierna>Mae geri</Tecnica_Pierna>
        <Teoria>Basica</Teoria>
        <Kata>Juroku</Kata>
        <Kumite>Ippon Kumite</Kumite>
</CinturonNegros>

<CinturonNegroPrimerAny>
        <Tecnica_Defensa>UKE WAZA</Tecnica_Defensa>
        <Tecnica_Pierna>GERI WAZA</Tecnica_Pierna>
        <Tecnica_DirectaIndirecta>TSUKI-UCHI WAZA </Tecnica_DirectaIndirecta>
        <Tecnica_Combinada>UKE WAZA y GERI WAZA</Tecnica_Combinada>
        <Teoria>Avanzada</Teoria>
        <Kata>Juroku</Kata>
        <Kumite>Ippon Kumite</Kumite>
        <Aplicacion_Tecnica>Aplicar</Aplicacion_Tecnica>
</CinturonNegroPrimerAny>

<CinturonNegroSegundoAny>
        <Tecnica_Base>Kakato geri</Tecnica_Base>
        <Tecnica_Directa>TSUKI-UCHI WAZA</Tecnica_Directa>
        <Tecnica_IndirectaCircular>TSUKI-UCHI WAZA</Tecnica_IndirectaCircular>
        <Tecnica_Pierna>Mae geri</Tecnica_Pierna>
        <Tecnica_Combinada>UKE WAZA y GERI WAZA</Tecnica_Combinada>
        <Teoria>Avanzada</Teoria>
        <Kata>Juroku</Kata>
        <Kumite>Ippon Kumite</Kumite>
        <Campeonatos>Karate</Campeonatos>
        <Tecnicas>Kakato geri</Tecnicas>
        <Aplicacion_Tecnica></Aplicacion_Tecnica>
        <Demo_libre>Accion Libre</Demo_libre>
</CinturonNegroSegundoAny>

<CinturonNegroTercerAny>
        <Variaciones_Tecnica>Muchas variaciones</Variaciones_Tecnica>
        <Teoria>Avanzada</Teoria>
        <Kata>Juroku</Kata>
        <Kumite>Ippon Kumite</Kumite>
        <Campeonatos>Karate</Campeonatos>
        <Tecnicas>Kakato geri</Tecnicas>
        <Aplicaciones>Aplicar</Aplicaciones>
        <Aplicacion_Tecnica>Aplicar</Aplicacion_Tecnica>
        <Demo_libre>Accion Libre</Demo_libre>
</CinturonNegroTercerAny>

<CinturonNegroCuartoAny>
        <Kata>Juroku</Kata>
        <Kumite>Ippon Kumite</Kumite>
        <Coloquio>Mentalizar</Coloquio>
        <Aplicacion_Tecnica>Aplicar</Aplicacion_Tecnica>
        <Demo_libre>Accion libre</Demo_libre>
</CinturonNegroCuartoAny>

<QuintoAnySuperior>
        <Kata>Juroku</Kata>
        <Coloquio>Mentalizar</Coloquio>
</QuintoAnySuperior>

<CriteriosValoraciones>
        <Id_aspirante>001</Id_aspirante>
</CriteriosValoraciones>

</examenddl>
